[package]
name = "envelope"
version = "0.1.0"
authors = ["arcnemesys <accelerenzo@proton.me>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
env_logger = "0.11.3"
ratatui = "0.27.0"
terminal_size = "0.3.0"
